sudo: required
services:
    - docker

before_install:
    - docker build -t krajavar/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true krajavar/react-test npm test

after_success:
    - docker build -t krajavar/multi-client ./client
    - docker build -t krajavar/multi-nginx ./nginx
    - docker build -t krajavar/multi-server ./server
    - docker build -t krajavar/multi-worker ./worker
